/** Tokens de injeção de dependência do módulo comercial. */
export const PEDIDO_REPOSITORY = 'PEDIDO_REPOSITORY'
export const ITEM_PEDIDO_REPOSITORY = 'ITEM_PEDIDO_REPOSITORY'
export const VENDA_REPOSITORY = 'VENDA_REPOSITORY'

export const CRIAR_PEDIDO_USE_CASE = 'CRIAR_PEDIDO_USE_CASE'
export const LISTAR_PEDIDOS_USE_CASE = 'LISTAR_PEDIDOS_USE_CASE'
export const BUSCAR_PEDIDO_USE_CASE = 'BUSCAR_PEDIDO_USE_CASE'
export const CONFIRMAR_PEDIDO_USE_CASE = 'CONFIRMAR_PEDIDO_USE_CASE'
export const CANCELAR_PEDIDO_USE_CASE = 'CANCELAR_PEDIDO_USE_CASE'
export const MARCAR_ENVIADO_USE_CASE = 'MARCAR_ENVIADO_USE_CASE'
export const REGISTRAR_VENDA_USE_CASE = 'REGISTRAR_VENDA_USE_CASE'
export const LISTAR_VENDAS_USE_CASE = 'LISTAR_VENDAS_USE_CASE'
