import { Module } from '@nestjs/common'
import { PrismaModule } from '../../shared/database/prisma.module'
import { TiposMateriaPrimaController } from './adapters/in/http/TiposMateriaPrimaController'
import { ColheitasController } from './adapters/in/http/ColheitasController'
import { FloradasController } from './adapters/in/http/FloradasController'
import { SafrasController } from './adapters/in/http/SafrasController'
import { CampanhasController } from './adapters/in/http/CampanhasController'
import { PrismaComposicaoProdutoRepository, PrismaEstoqueProdutoRepository, PrismaProdutoRepository } from '../catalogo/adapters/out/persistence'
import { PrismaEquipamentoRepository } from '../patrimonio/adapters/out/persistence'
import { PrismaItemPedidoRepository } from '../comercial/adapters/out/persistence'
import {
  PrismaApuracaoCampanhaRepository,
  PrismaCampanhaRepository,
  PrismaColheitaRepository,
  PrismaContribuicaoRepository,
  PrismaCotaRepository,
  PrismaCustoCampanhaRepository,
  PrismaEstoqueCampanhaRepository,
  PrismaEstoqueMateriaPrimaRepository,
  PrismaFloradaRepository,
  PrismaItemAquisicaoRepository,
  PrismaMovimentoFinanceiroRepository,
  PrismaOrdemProducaoRepository,
  PrismaSafraRepository,
  PrismaTipoMateriaPrimaRepository,
} from './adapters/out/persistence'
import { PrismaPedidoAquisicaoRepository } from './adapters/out/persistence/PrismaPedidoAquisicaoRepository'
import {
  AdicionarItemAquisicaoUseCase,
  AtualizarContribuicaoUseCase,
  AtualizarItemAquisicaoUseCase,
  AtualizarSafraUseCase,
  DeletarSafraUseCase,
  CriarFloradaUseCase,
  ListarFlораdasUseCase,
  BuscarCampanhaUseCase,
  BuscarSafraUseCase,
  BuscarTipoMateriaPrimaUseCase,
  DeletarTipoMateriaPrimaUseCase,
  CalcularConsumoUseCase,
  CalcularDistribuicaoPreviewUseCase,
  CancelarCampanhaUseCase,
  DeletarCampanhaUseCase,
  CancelarCotaUseCase,
  ConcluirCampanhaUseCase,
  DeletarOrdemProducaoUseCase,
  AtualizarReceitaCampanhaUseCase,
  PreviewRateioCampanhaUseCase,
  ConfirmarCotaUseCase,
  ConsultarApuracaoUseCase,
  ListarEstoqueCampanhaUseCase,
  ConsultarEstoqueUseCase,
  CriarCampanhaUseCase,
  CriarColheitaUseCase,
  CriarOrdemProducaoUseCase,
  CriarSafraUseCase,
  CriarTipoMateriaPrimaUseCase,
  DistribuirItensUseCase,
  EncerrarSafraUseCase,
  ExecutarOrdemProducaoUseCase,
  IniciarCampanhaUseCase,
  IniciarSafraUseCase,
  ListarCampanhasUseCase,
  ListarColheitasUseCase,
  ListarColheitasPorAssociadoUseCase,
  ListarColheitasPorCampanhaUseCase,
  DeletarColheitaUseCase,
  DeletarItemPoolUseCase,
  ListarConsumiveisUseCase,
  ListarContribuicoesPorAssociadoUseCase,
  ListarContribuicoesPorCampanhaUseCase,
  ListarCotasPorCampanhaUseCase,
  ListarCustosPorCampanhaUseCase,
  ListarItensAquisicaoUseCase,
  ListarOrdensPorCampanhaUseCase,
  ListarSafrasUseCase,
  ListarTiposMateriaPrimaUseCase,
  LiquidarCampanhaUseCase,
  MigrarInsumosConsumiveisUseCase,
  MinhasCotasUseCase,
  RastrearCampanhaUseCase,
  RegistrarContribuicaoUseCase,
  RegistrarCotaUseCase,
  RegistrarCustoUseCase,
  RegistrarEntradaConsumivelUseCase,
  RemoverContribuicaoUseCase,
  RemoverCustoUseCase,
  RemoverItemAquisicaoUseCase,
  ResumoCaptacaoUseCase,
  RegistrarPedidoAquisicaoUseCase,
  ListarPedidosAquisicaoUseCase,
  ConfirmarPagamentoPedidoUseCase,
  MarcarPedidoEntregueUseCase,
} from './application/use-cases'
import {
  ADICIONAR_ITEM_AQUISICAO_USE_CASE,
  APURACAO_CAMPANHA_REPOSITORY,
  CRIAR_FLORADA_USE_CASE,
  LISTAR_FLORADAS_USE_CASE,
  FLORADA_REPOSITORY,
  ATUALIZAR_CONTRIBUICAO_USE_CASE,
  ATUALIZAR_ITEM_AQUISICAO_USE_CASE,
  ATUALIZAR_SAFRA_USE_CASE,
  DELETAR_SAFRA_USE_CASE,
  BUSCAR_CAMPANHA_USE_CASE,
  BUSCAR_SAFRA_USE_CASE,
  BUSCAR_TIPO_MATERIA_PRIMA_USE_CASE,
  DELETAR_TIPO_MATERIA_PRIMA_USE_CASE,
  CALCULAR_CONSUMO_USE_CASE,
  CALCULAR_DISTRIBUICAO_PREVIEW_USE_CASE,
  CAMPANHA_REPOSITORY,
  CANCELAR_CAMPANHA_USE_CASE,
  DELETAR_CAMPANHA_USE_CASE,
  ATUALIZAR_RECEITA_CAMPANHA_USE_CASE,
  PREVIEW_RATEIO_CAMPANHA_USE_CASE,
  CANCELAR_COTA_USE_CASE,
  COLHEITA_REPOSITORY,
  CONCLUIR_CAMPANHA_USE_CASE,
  DELETAR_ORDEM_PRODUCAO_USE_CASE,
  CONFIRMAR_COTA_USE_CASE,
  CONSULTAR_APURACAO_USE_CASE,
  CONSULTAR_ESTOQUE_USE_CASE,
  CONTRIBUICAO_REPOSITORY,
  COTA_REPOSITORY,
  CRIAR_CAMPANHA_USE_CASE,
  CRIAR_COLHEITA_USE_CASE,
  CRIAR_ORDEM_PRODUCAO_USE_CASE,
  CRIAR_SAFRA_USE_CASE,
  CRIAR_TIPO_MATERIA_PRIMA_USE_CASE,
  CUSTO_CAMPANHA_REPOSITORY,
  DISTRIBUIR_ITENS_USE_CASE,
  ENCERRAR_SAFRA_USE_CASE,
  ESTOQUE_MATERIA_PRIMA_REPOSITORY,
  ESTOQUE_CAMPANHA_REPOSITORY,
  LISTAR_ESTOQUE_CAMPANHA_USE_CASE,
  EXECUTAR_ORDEM_PRODUCAO_USE_CASE,
  INICIAR_CAMPANHA_USE_CASE,
  INICIAR_SAFRA_USE_CASE,
  ITEM_AQUISICAO_REPOSITORY,
  ITEM_PEDIDO_REPOSITORY,
  LISTAR_CAMPANHAS_USE_CASE,
  LISTAR_COLHEITAS_USE_CASE,
  LISTAR_COLHEITAS_ASSOCIADO_USE_CASE,
  LISTAR_COLHEITAS_CAMPANHA_USE_CASE,
  DELETAR_COLHEITA_USE_CASE,
  DELETAR_ITEM_POOL_USE_CASE,
  LISTAR_CONSUMIVEIS_USE_CASE,
  LISTAR_CONTRIBUICOES_ASSOCIADO_USE_CASE,
  LISTAR_CONTRIBUICOES_CAMPANHA_USE_CASE,
  LISTAR_COTAS_CAMPANHA_USE_CASE,
  LISTAR_CUSTOS_CAMPANHA_USE_CASE,
  LISTAR_ITENS_AQUISICAO_USE_CASE,
  LISTAR_ORDENS_CAMPANHA_USE_CASE,
  LISTAR_SAFRAS_USE_CASE,
  LISTAR_TIPOS_MATERIA_PRIMA_USE_CASE,
  LIQUIDAR_CAMPANHA_USE_CASE,
  MIGRAR_INSUMOS_USE_CASE,
  MINHAS_COTAS_USE_CASE,
  MOVIMENTO_FINANCEIRO_REPOSITORY,
  ORDEM_PRODUCAO_REPOSITORY,
  RASTREAR_CAMPANHA_USE_CASE,
  REGISTRAR_CONTRIBUICAO_USE_CASE,
  REGISTRAR_COTA_USE_CASE,
  REGISTRAR_CUSTO_USE_CASE,
  REGISTRAR_ENTRADA_CONSUMIVEL_USE_CASE,
  REMOVER_CONTRIBUICAO_USE_CASE,
  REMOVER_CUSTO_USE_CASE,
  REMOVER_ITEM_AQUISICAO_USE_CASE,
  RESUMO_CAPTACAO_USE_CASE,
  SAFRA_REPOSITORY,
  TIPO_MATERIA_PRIMA_REPOSITORY,
  PEDIDO_AQUISICAO_REPOSITORY,
  REGISTRAR_PEDIDO_AQUISICAO_USE_CASE,
  LISTAR_PEDIDOS_AQUISICAO_USE_CASE,
  CONFIRMAR_PAGAMENTO_PEDIDO_USE_CASE,
  MARCAR_PEDIDO_ENTREGUE_USE_CASE,
} from './producao.tokens'

/** Catalogo string tokens — same values as catalogo.tokens.ts, avoids circular import. */
const COMPOSICAO_PRODUTO_REPOSITORY = 'COMPOSICAO_PRODUTO_REPOSITORY'
const ESTOQUE_PRODUTO_REPOSITORY = 'ESTOQUE_PRODUTO_REPOSITORY'
const PRODUTO_REPOSITORY = 'PRODUTO_REPOSITORY'
/** Patrimonio string token — same value as patrimonio.tokens.ts, avoids circular import. */
const EQUIPAMENTO_REPOSITORY = 'EQUIPAMENTO_REPOSITORY'
@Module({
  imports: [PrismaModule],
  controllers: [TiposMateriaPrimaController, ColheitasController, FloradasController, SafrasController, CampanhasController],
  providers: [
    // Repositórios
    { provide: FLORADA_REPOSITORY, useClass: PrismaFloradaRepository },
    { provide: TIPO_MATERIA_PRIMA_REPOSITORY, useClass: PrismaTipoMateriaPrimaRepository },
    { provide: COLHEITA_REPOSITORY, useClass: PrismaColheitaRepository },
    { provide: ESTOQUE_MATERIA_PRIMA_REPOSITORY, useClass: PrismaEstoqueMateriaPrimaRepository },
    // Repositórios — novo modelo
    { provide: SAFRA_REPOSITORY, useClass: PrismaSafraRepository },
    { provide: CAMPANHA_REPOSITORY, useClass: PrismaCampanhaRepository },
    { provide: CONTRIBUICAO_REPOSITORY, useClass: PrismaContribuicaoRepository },
    { provide: COTA_REPOSITORY, useClass: PrismaCotaRepository },
    { provide: ORDEM_PRODUCAO_REPOSITORY, useClass: PrismaOrdemProducaoRepository },
    { provide: CUSTO_CAMPANHA_REPOSITORY, useClass: PrismaCustoCampanhaRepository },
    { provide: APURACAO_CAMPANHA_REPOSITORY, useClass: PrismaApuracaoCampanhaRepository },
    { provide: MOVIMENTO_FINANCEIRO_REPOSITORY, useClass: PrismaMovimentoFinanceiroRepository },
    { provide: ITEM_AQUISICAO_REPOSITORY, useClass: PrismaItemAquisicaoRepository },
    { provide: ESTOQUE_CAMPANHA_REPOSITORY, useClass: PrismaEstoqueCampanhaRepository },
    { provide: PEDIDO_AQUISICAO_REPOSITORY, useClass: PrismaPedidoAquisicaoRepository },
    // Repositórios — cross-module (tokens locais, sem import circular)
    { provide: COMPOSICAO_PRODUTO_REPOSITORY, useClass: PrismaComposicaoProdutoRepository },
    { provide: ESTOQUE_PRODUTO_REPOSITORY, useClass: PrismaEstoqueProdutoRepository },
    { provide: PRODUTO_REPOSITORY, useClass: PrismaProdutoRepository },
    { provide: EQUIPAMENTO_REPOSITORY, useClass: PrismaEquipamentoRepository },
    { provide: ITEM_PEDIDO_REPOSITORY, useClass: PrismaItemPedidoRepository },
    // Use cases — florada
    { provide: CRIAR_FLORADA_USE_CASE, useClass: CriarFloradaUseCase },
    { provide: LISTAR_FLORADAS_USE_CASE, useClass: ListarFlораdasUseCase },
    // Use cases — tipo matéria prima e colheita
    { provide: CRIAR_TIPO_MATERIA_PRIMA_USE_CASE, useClass: CriarTipoMateriaPrimaUseCase },
    { provide: LISTAR_TIPOS_MATERIA_PRIMA_USE_CASE, useClass: ListarTiposMateriaPrimaUseCase },
    { provide: BUSCAR_TIPO_MATERIA_PRIMA_USE_CASE, useClass: BuscarTipoMateriaPrimaUseCase },
    { provide: DELETAR_TIPO_MATERIA_PRIMA_USE_CASE, useClass: DeletarTipoMateriaPrimaUseCase },
    { provide: CRIAR_COLHEITA_USE_CASE, useClass: CriarColheitaUseCase },
    { provide: LISTAR_COLHEITAS_USE_CASE, useClass: ListarColheitasUseCase },
    { provide: LISTAR_COLHEITAS_ASSOCIADO_USE_CASE, useClass: ListarColheitasPorAssociadoUseCase },
    { provide: LISTAR_COLHEITAS_CAMPANHA_USE_CASE, useClass: ListarColheitasPorCampanhaUseCase },
    { provide: DELETAR_COLHEITA_USE_CASE, useClass: DeletarColheitaUseCase },
    { provide: DELETAR_ITEM_POOL_USE_CASE, useClass: DeletarItemPoolUseCase },
    { provide: CONSULTAR_ESTOQUE_USE_CASE, useClass: ConsultarEstoqueUseCase },
    // Use cases — safra
    { provide: CRIAR_SAFRA_USE_CASE, useClass: CriarSafraUseCase },
    { provide: LISTAR_SAFRAS_USE_CASE, useClass: ListarSafrasUseCase },
    { provide: BUSCAR_SAFRA_USE_CASE, useClass: BuscarSafraUseCase },
    { provide: ATUALIZAR_SAFRA_USE_CASE, useClass: AtualizarSafraUseCase },
    { provide: INICIAR_SAFRA_USE_CASE, useClass: IniciarSafraUseCase },
    { provide: ENCERRAR_SAFRA_USE_CASE, useClass: EncerrarSafraUseCase },
    { provide: DELETAR_SAFRA_USE_CASE, useClass: DeletarSafraUseCase },
    // Use cases — campanha
    { provide: CRIAR_CAMPANHA_USE_CASE, useClass: CriarCampanhaUseCase },
    { provide: LISTAR_CAMPANHAS_USE_CASE, useClass: ListarCampanhasUseCase },
    { provide: BUSCAR_CAMPANHA_USE_CASE, useClass: BuscarCampanhaUseCase },
    { provide: INICIAR_CAMPANHA_USE_CASE, useClass: IniciarCampanhaUseCase },
    { provide: CONCLUIR_CAMPANHA_USE_CASE, useClass: ConcluirCampanhaUseCase },
    { provide: CANCELAR_CAMPANHA_USE_CASE, useClass: CancelarCampanhaUseCase },
    { provide: DELETAR_CAMPANHA_USE_CASE, useClass: DeletarCampanhaUseCase },
    { provide: ATUALIZAR_RECEITA_CAMPANHA_USE_CASE, useClass: AtualizarReceitaCampanhaUseCase },
    { provide: PREVIEW_RATEIO_CAMPANHA_USE_CASE, useClass: PreviewRateioCampanhaUseCase },
    { provide: LIQUIDAR_CAMPANHA_USE_CASE, useClass: LiquidarCampanhaUseCase },
    { provide: CONSULTAR_APURACAO_USE_CASE, useClass: ConsultarApuracaoUseCase },
    // Use cases — contribuição
    { provide: REGISTRAR_CONTRIBUICAO_USE_CASE, useClass: RegistrarContribuicaoUseCase },
    { provide: LISTAR_CONTRIBUICOES_CAMPANHA_USE_CASE, useClass: ListarContribuicoesPorCampanhaUseCase },
    { provide: LISTAR_CONTRIBUICOES_ASSOCIADO_USE_CASE, useClass: ListarContribuicoesPorAssociadoUseCase },
    { provide: ATUALIZAR_CONTRIBUICAO_USE_CASE, useClass: AtualizarContribuicaoUseCase },
    { provide: REMOVER_CONTRIBUICAO_USE_CASE, useClass: RemoverContribuicaoUseCase },
    // Use cases — cota
    { provide: REGISTRAR_COTA_USE_CASE, useClass: RegistrarCotaUseCase },
    { provide: CONFIRMAR_COTA_USE_CASE, useClass: ConfirmarCotaUseCase },
    { provide: CANCELAR_COTA_USE_CASE, useClass: CancelarCotaUseCase },
    { provide: LISTAR_COTAS_CAMPANHA_USE_CASE, useClass: ListarCotasPorCampanhaUseCase },
    { provide: MINHAS_COTAS_USE_CASE, useClass: MinhasCotasUseCase },
    { provide: RESUMO_CAPTACAO_USE_CASE, useClass: ResumoCaptacaoUseCase },
    // Use cases — item aquisição
    { provide: ADICIONAR_ITEM_AQUISICAO_USE_CASE, useClass: AdicionarItemAquisicaoUseCase },
    { provide: LISTAR_ITENS_AQUISICAO_USE_CASE, useClass: ListarItensAquisicaoUseCase },
    { provide: REMOVER_ITEM_AQUISICAO_USE_CASE, useClass: RemoverItemAquisicaoUseCase },
    { provide: ATUALIZAR_ITEM_AQUISICAO_USE_CASE, useClass: AtualizarItemAquisicaoUseCase },
    { provide: DISTRIBUIR_ITENS_USE_CASE, useClass: DistribuirItensUseCase },
    { provide: CALCULAR_DISTRIBUICAO_PREVIEW_USE_CASE, useClass: CalcularDistribuicaoPreviewUseCase },
    // Use cases — ordem de produção
    { provide: CRIAR_ORDEM_PRODUCAO_USE_CASE, useClass: CriarOrdemProducaoUseCase },
    { provide: EXECUTAR_ORDEM_PRODUCAO_USE_CASE, useClass: ExecutarOrdemProducaoUseCase },
    { provide: DELETAR_ORDEM_PRODUCAO_USE_CASE, useClass: DeletarOrdemProducaoUseCase },
    { provide: LISTAR_ORDENS_CAMPANHA_USE_CASE, useClass: ListarOrdensPorCampanhaUseCase },
    { provide: CALCULAR_CONSUMO_USE_CASE, useClass: CalcularConsumoUseCase },
    // Use cases — custo de campanha
    { provide: REGISTRAR_CUSTO_USE_CASE, useClass: RegistrarCustoUseCase },
    { provide: LISTAR_CUSTOS_CAMPANHA_USE_CASE, useClass: ListarCustosPorCampanhaUseCase },
    { provide: REMOVER_CUSTO_USE_CASE, useClass: RemoverCustoUseCase },
    // Use cases — consumíveis
    { provide: REGISTRAR_ENTRADA_CONSUMIVEL_USE_CASE, useClass: RegistrarEntradaConsumivelUseCase },
    { provide: LISTAR_CONSUMIVEIS_USE_CASE, useClass: ListarConsumiveisUseCase },
    { provide: MIGRAR_INSUMOS_USE_CASE, useClass: MigrarInsumosConsumiveisUseCase },
    { provide: LISTAR_ESTOQUE_CAMPANHA_USE_CASE, useClass: ListarEstoqueCampanhaUseCase },
    // Use cases — rastreabilidade
    { provide: RASTREAR_CAMPANHA_USE_CASE, useClass: RastrearCampanhaUseCase },
    // Use cases — pedido aquisição
    { provide: REGISTRAR_PEDIDO_AQUISICAO_USE_CASE, useClass: RegistrarPedidoAquisicaoUseCase },
    { provide: LISTAR_PEDIDOS_AQUISICAO_USE_CASE, useClass: ListarPedidosAquisicaoUseCase },
    { provide: CONFIRMAR_PAGAMENTO_PEDIDO_USE_CASE, useClass: ConfirmarPagamentoPedidoUseCase },
    { provide: MARCAR_PEDIDO_ENTREGUE_USE_CASE, useClass: MarcarPedidoEntregueUseCase },
  ],
  exports: [
    COLHEITA_REPOSITORY,
    ESTOQUE_MATERIA_PRIMA_REPOSITORY,
    SAFRA_REPOSITORY,
    CAMPANHA_REPOSITORY,
  ],
})
/** Módulo NestJS de produção — tipos de matéria-prima, colheitas, safras, campanhas e ordens de produção. */
export class ProducaoModule {}
