/** Tokens de injeção de dependência do módulo de produção. */
export const TIPO_MATERIA_PRIMA_REPOSITORY = 'TIPO_MATERIA_PRIMA_REPOSITORY'
export const COLHEITA_REPOSITORY = 'COLHEITA_REPOSITORY'
export const LOTE_PRODUCAO_REPOSITORY = 'LOTE_PRODUCAO_REPOSITORY'
export const PARTICIPACAO_LOTE_REPOSITORY = 'PARTICIPACAO_LOTE_REPOSITORY'
export const ESTOQUE_MATERIA_PRIMA_REPOSITORY = 'ESTOQUE_MATERIA_PRIMA_REPOSITORY'

export const CRIAR_LOTE_USE_CASE = 'CRIAR_LOTE_USE_CASE'
export const LISTAR_LOTES_USE_CASE = 'LISTAR_LOTES_USE_CASE'
export const BUSCAR_LOTE_USE_CASE = 'BUSCAR_LOTE_USE_CASE'
export const ENCERRAR_LOTE_USE_CASE = 'ENCERRAR_LOTE_USE_CASE'
export const REGISTRAR_PARTICIPACAO_USE_CASE = 'REGISTRAR_PARTICIPACAO_USE_CASE'
export const LISTAR_PARTICIPACOES_LOTE_USE_CASE = 'LISTAR_PARTICIPACOES_LOTE_USE_CASE'
export const ATUALIZAR_PARTICIPACAO_USE_CASE = 'ATUALIZAR_PARTICIPACAO_USE_CASE'
export const CALCULAR_RATEIO_USE_CASE = 'CALCULAR_RATEIO_USE_CASE'
export const CONSULTAR_ESTOQUE_USE_CASE = 'CONSULTAR_ESTOQUE_USE_CASE'

export const CRIAR_TIPO_MATERIA_PRIMA_USE_CASE = 'CRIAR_TIPO_MATERIA_PRIMA_USE_CASE'
export const LISTAR_TIPOS_MATERIA_PRIMA_USE_CASE = 'LISTAR_TIPOS_MATERIA_PRIMA_USE_CASE'
export const BUSCAR_TIPO_MATERIA_PRIMA_USE_CASE = 'BUSCAR_TIPO_MATERIA_PRIMA_USE_CASE'

export const CRIAR_COLHEITA_USE_CASE = 'CRIAR_COLHEITA_USE_CASE'
export const LISTAR_COLHEITAS_ASSOCIADO_USE_CASE = 'LISTAR_COLHEITAS_ASSOCIADO_USE_CASE'
export const LISTAR_COLHEITAS_LOTE_USE_CASE = 'LISTAR_COLHEITAS_LOTE_USE_CASE'
