/** Tokens de injeção de dependência do módulo de produção. */

// Repositórios
export const FLORADA_REPOSITORY = 'FLORADA_REPOSITORY'
export const TIPO_MATERIA_PRIMA_REPOSITORY = 'TIPO_MATERIA_PRIMA_REPOSITORY'
export const COLHEITA_REPOSITORY = 'COLHEITA_REPOSITORY'
export const ESTOQUE_MATERIA_PRIMA_REPOSITORY = 'ESTOQUE_MATERIA_PRIMA_REPOSITORY'
export const SAFRA_REPOSITORY = 'SAFRA_REPOSITORY'
export const CAMPANHA_REPOSITORY = 'CAMPANHA_REPOSITORY'
export const CONTRIBUICAO_REPOSITORY = 'CONTRIBUICAO_REPOSITORY'
export const COTA_REPOSITORY = 'COTA_REPOSITORY'
export const ORDEM_PRODUCAO_REPOSITORY = 'ORDEM_PRODUCAO_REPOSITORY'
export const CUSTO_CAMPANHA_REPOSITORY = 'CUSTO_CAMPANHA_REPOSITORY'
export const APURACAO_CAMPANHA_REPOSITORY = 'APURACAO_CAMPANHA_REPOSITORY'
export const MOVIMENTO_FINANCEIRO_REPOSITORY = 'MOVIMENTO_FINANCEIRO_REPOSITORY'

// Use cases — estoque
export const CONSULTAR_ESTOQUE_USE_CASE = 'CONSULTAR_ESTOQUE_USE_CASE'
export const DELETAR_ITEM_POOL_USE_CASE = 'DELETAR_ITEM_POOL_USE_CASE'

// Use cases — florada
export const CRIAR_FLORADA_USE_CASE = 'CRIAR_FLORADA_USE_CASE'
export const LISTAR_FLORADAS_USE_CASE = 'LISTAR_FLORADAS_USE_CASE'

// Use cases — tipo matéria prima
export const CRIAR_TIPO_MATERIA_PRIMA_USE_CASE = 'CRIAR_TIPO_MATERIA_PRIMA_USE_CASE'
export const LISTAR_TIPOS_MATERIA_PRIMA_USE_CASE = 'LISTAR_TIPOS_MATERIA_PRIMA_USE_CASE'
export const BUSCAR_TIPO_MATERIA_PRIMA_USE_CASE = 'BUSCAR_TIPO_MATERIA_PRIMA_USE_CASE'
export const DELETAR_TIPO_MATERIA_PRIMA_USE_CASE = 'DELETAR_TIPO_MATERIA_PRIMA_USE_CASE'

// Use cases — colheita
export const CRIAR_COLHEITA_USE_CASE = 'CRIAR_COLHEITA_USE_CASE'
export const LISTAR_COLHEITAS_USE_CASE = 'LISTAR_COLHEITAS_USE_CASE'
export const LISTAR_COLHEITAS_ASSOCIADO_USE_CASE = 'LISTAR_COLHEITAS_ASSOCIADO_USE_CASE'
export const LISTAR_COLHEITAS_CAMPANHA_USE_CASE = 'LISTAR_COLHEITAS_CAMPANHA_USE_CASE'
export const DELETAR_COLHEITA_USE_CASE = 'DELETAR_COLHEITA_USE_CASE'

// Use cases — safra
export const CRIAR_SAFRA_USE_CASE = 'CRIAR_SAFRA_USE_CASE'
export const LISTAR_SAFRAS_USE_CASE = 'LISTAR_SAFRAS_USE_CASE'
export const BUSCAR_SAFRA_USE_CASE = 'BUSCAR_SAFRA_USE_CASE'
export const ATUALIZAR_SAFRA_USE_CASE = 'ATUALIZAR_SAFRA_USE_CASE'
export const INICIAR_SAFRA_USE_CASE = 'INICIAR_SAFRA_USE_CASE'
export const ENCERRAR_SAFRA_USE_CASE = 'ENCERRAR_SAFRA_USE_CASE'
export const DELETAR_SAFRA_USE_CASE = 'DELETAR_SAFRA_USE_CASE'

// Use cases — campanha
export const CRIAR_CAMPANHA_USE_CASE = 'CRIAR_CAMPANHA_USE_CASE'
export const LISTAR_CAMPANHAS_USE_CASE = 'LISTAR_CAMPANHAS_USE_CASE'
export const BUSCAR_CAMPANHA_USE_CASE = 'BUSCAR_CAMPANHA_USE_CASE'
export const INICIAR_CAMPANHA_USE_CASE = 'INICIAR_CAMPANHA_USE_CASE'
export const CONCLUIR_CAMPANHA_USE_CASE = 'CONCLUIR_CAMPANHA_USE_CASE'
export const LIQUIDAR_CAMPANHA_USE_CASE = 'LIQUIDAR_CAMPANHA_USE_CASE'
export const CANCELAR_CAMPANHA_USE_CASE = 'CANCELAR_CAMPANHA_USE_CASE'
export const DELETAR_CAMPANHA_USE_CASE = 'DELETAR_CAMPANHA_USE_CASE'
export const ATUALIZAR_RECEITA_CAMPANHA_USE_CASE = 'ATUALIZAR_RECEITA_CAMPANHA_USE_CASE'
export const PREVIEW_RATEIO_CAMPANHA_USE_CASE = 'PREVIEW_RATEIO_CAMPANHA_USE_CASE'

// Use cases — contribuição
export const REGISTRAR_CONTRIBUICAO_USE_CASE = 'REGISTRAR_CONTRIBUICAO_USE_CASE'
export const LISTAR_CONTRIBUICOES_CAMPANHA_USE_CASE = 'LISTAR_CONTRIBUICOES_CAMPANHA_USE_CASE'
export const LISTAR_CONTRIBUICOES_ASSOCIADO_USE_CASE = 'LISTAR_CONTRIBUICOES_ASSOCIADO_USE_CASE'
export const ATUALIZAR_CONTRIBUICAO_USE_CASE = 'ATUALIZAR_CONTRIBUICAO_USE_CASE'
export const REMOVER_CONTRIBUICAO_USE_CASE = 'REMOVER_CONTRIBUICAO_USE_CASE'

// Use cases — cota
export const REGISTRAR_COTA_USE_CASE = 'REGISTRAR_COTA_USE_CASE'
export const CONFIRMAR_COTA_USE_CASE = 'CONFIRMAR_COTA_USE_CASE'
export const CANCELAR_COTA_USE_CASE = 'CANCELAR_COTA_USE_CASE'
export const LISTAR_COTAS_CAMPANHA_USE_CASE = 'LISTAR_COTAS_CAMPANHA_USE_CASE'
export const MINHAS_COTAS_USE_CASE = 'MINHAS_COTAS_USE_CASE'
export const RESUMO_CAPTACAO_USE_CASE = 'RESUMO_CAPTACAO_USE_CASE'

// Use cases — ordem produção
export const CRIAR_ORDEM_PRODUCAO_USE_CASE = 'CRIAR_ORDEM_PRODUCAO_USE_CASE'
export const EXECUTAR_ORDEM_PRODUCAO_USE_CASE = 'EXECUTAR_ORDEM_PRODUCAO_USE_CASE'
export const DELETAR_ORDEM_PRODUCAO_USE_CASE = 'DELETAR_ORDEM_PRODUCAO_USE_CASE'
export const LISTAR_ORDENS_CAMPANHA_USE_CASE = 'LISTAR_ORDENS_CAMPANHA_USE_CASE'
export const CALCULAR_CONSUMO_USE_CASE = 'CALCULAR_CONSUMO_USE_CASE'

// Use cases — custo campanha
export const REGISTRAR_CUSTO_USE_CASE = 'REGISTRAR_CUSTO_USE_CASE'
export const LISTAR_CUSTOS_CAMPANHA_USE_CASE = 'LISTAR_CUSTOS_CAMPANHA_USE_CASE'
export const REMOVER_CUSTO_USE_CASE = 'REMOVER_CUSTO_USE_CASE'

// Repositório — item aquisição
export const ITEM_AQUISICAO_REPOSITORY = 'ITEM_AQUISICAO_REPOSITORY'
export const ITEM_PEDIDO_REPOSITORY = 'ITEM_PEDIDO_REPOSITORY'
export const ESTOQUE_CAMPANHA_REPOSITORY = 'ESTOQUE_CAMPANHA_REPOSITORY'

// Use cases — item aquisição
export const ADICIONAR_ITEM_AQUISICAO_USE_CASE = 'ADICIONAR_ITEM_AQUISICAO_USE_CASE'
export const LISTAR_ITENS_AQUISICAO_USE_CASE = 'LISTAR_ITENS_AQUISICAO_USE_CASE'
export const REMOVER_ITEM_AQUISICAO_USE_CASE = 'REMOVER_ITEM_AQUISICAO_USE_CASE'
export const ATUALIZAR_ITEM_AQUISICAO_USE_CASE = 'ATUALIZAR_ITEM_AQUISICAO_USE_CASE'
export const DISTRIBUIR_ITENS_USE_CASE = 'DISTRIBUIR_ITENS_USE_CASE'
export const CALCULAR_DISTRIBUICAO_PREVIEW_USE_CASE = 'CALCULAR_DISTRIBUICAO_PREVIEW_USE_CASE'

// Use cases — consumíveis
export const REGISTRAR_ENTRADA_CONSUMIVEL_USE_CASE = 'REGISTRAR_ENTRADA_CONSUMIVEL_USE_CASE'
export const LISTAR_CONSUMIVEIS_USE_CASE = 'LISTAR_CONSUMIVEIS_USE_CASE'
export const MIGRAR_INSUMOS_USE_CASE = 'MIGRAR_INSUMOS_USE_CASE'

// Use cases — rastreabilidade
export const RASTREAR_CAMPANHA_USE_CASE = 'RASTREAR_CAMPANHA_USE_CASE'

// Use cases — apuração
export const CONSULTAR_APURACAO_USE_CASE = 'CONSULTAR_APURACAO_USE_CASE'

// Use cases — estoque campanha
export const LISTAR_ESTOQUE_CAMPANHA_USE_CASE = 'LISTAR_ESTOQUE_CAMPANHA_USE_CASE'

// Repositório — pedido aquisição
export const PEDIDO_AQUISICAO_REPOSITORY = 'PEDIDO_AQUISICAO_REPOSITORY'

// Use cases — pedido aquisição
export const REGISTRAR_PEDIDO_AQUISICAO_USE_CASE = 'REGISTRAR_PEDIDO_AQUISICAO_USE_CASE'
export const LISTAR_PEDIDOS_AQUISICAO_USE_CASE = 'LISTAR_PEDIDOS_AQUISICAO_USE_CASE'
export const CONFIRMAR_PAGAMENTO_PEDIDO_USE_CASE = 'CONFIRMAR_PAGAMENTO_PEDIDO_USE_CASE'
export const MARCAR_PEDIDO_ENTREGUE_USE_CASE = 'MARCAR_PEDIDO_ENTREGUE_USE_CASE'
