export const AVISO_REPOSITORY = 'AVISO_REPOSITORY'

export const CRIAR_AVISO_USE_CASE = 'CRIAR_AVISO_USE_CASE'
export const LISTAR_AVISOS_USE_CASE = 'LISTAR_AVISOS_USE_CASE'
export const PUBLICAR_AVISO_USE_CASE = 'PUBLICAR_AVISO_USE_CASE'
export const DESPUBLICAR_AVISO_USE_CASE = 'DESPUBLICAR_AVISO_USE_CASE'
export const EXCLUIR_AVISO_USE_CASE = 'EXCLUIR_AVISO_USE_CASE'

export const SOLICITACAO_CONTATO_REPOSITORY = 'SOLICITACAO_CONTATO_REPOSITORY'
export const CRIAR_SOLICITACAO_CONTATO_USE_CASE = 'CRIAR_SOLICITACAO_CONTATO_USE_CASE'
export const LISTAR_SOLICITACOES_CONTATO_USE_CASE = 'LISTAR_SOLICITACOES_CONTATO_USE_CASE'
export const ATUALIZAR_STATUS_SOLICITACAO_CONTATO_USE_CASE = 'ATUALIZAR_STATUS_SOLICITACAO_CONTATO_USE_CASE'
export const EXCLUIR_SOLICITACAO_CONTATO_USE_CASE = 'EXCLUIR_SOLICITACAO_CONTATO_USE_CASE'
