export const EQUIPAMENTO_REPOSITORY = 'EQUIPAMENTO_REPOSITORY'

export const CRIAR_EQUIPAMENTO_USE_CASE = 'CRIAR_EQUIPAMENTO_USE_CASE'
export const LISTAR_EQUIPAMENTOS_USE_CASE = 'LISTAR_EQUIPAMENTOS_USE_CASE'
export const BUSCAR_EQUIPAMENTO_USE_CASE = 'BUSCAR_EQUIPAMENTO_USE_CASE'
export const ATUALIZAR_EQUIPAMENTO_USE_CASE = 'ATUALIZAR_EQUIPAMENTO_USE_CASE'
export const COLOCAR_EQUIPAMENTO_MANUTENCAO_USE_CASE = 'COLOCAR_EQUIPAMENTO_MANUTENCAO_USE_CASE'
