export const EQUIPAMENTO_REPOSITORY = 'EQUIPAMENTO_REPOSITORY'
export const INSUMO_REPOSITORY = 'INSUMO_REPOSITORY'
export const ATRIBUICAO_PATRIMONIO_REPOSITORY = 'ATRIBUICAO_PATRIMONIO_REPOSITORY'

export const CRIAR_EQUIPAMENTO_USE_CASE = 'CRIAR_EQUIPAMENTO_USE_CASE'
export const LISTAR_EQUIPAMENTOS_USE_CASE = 'LISTAR_EQUIPAMENTOS_USE_CASE'
export const BUSCAR_EQUIPAMENTO_USE_CASE = 'BUSCAR_EQUIPAMENTO_USE_CASE'
export const ATUALIZAR_EQUIPAMENTO_USE_CASE = 'ATUALIZAR_EQUIPAMENTO_USE_CASE'
export const COLOCAR_EQUIPAMENTO_MANUTENCAO_USE_CASE = 'COLOCAR_EQUIPAMENTO_MANUTENCAO_USE_CASE'

export const CRIAR_INSUMO_USE_CASE = 'CRIAR_INSUMO_USE_CASE'
export const LISTAR_INSUMOS_USE_CASE = 'LISTAR_INSUMOS_USE_CASE'
export const BUSCAR_INSUMO_USE_CASE = 'BUSCAR_INSUMO_USE_CASE'
export const ATUALIZAR_INSUMO_USE_CASE = 'ATUALIZAR_INSUMO_USE_CASE'
export const COLOCAR_INSUMO_MANUTENCAO_USE_CASE = 'COLOCAR_INSUMO_MANUTENCAO_USE_CASE'

export const ATRIBUIR_PATRIMONIO_USE_CASE = 'ATRIBUIR_PATRIMONIO_USE_CASE'
export const DEVOLVER_PATRIMONIO_USE_CASE = 'DEVOLVER_PATRIMONIO_USE_CASE'
export const LISTAR_ATRIBUICOES_ASSOCIADO_USE_CASE = 'LISTAR_ATRIBUICOES_ASSOCIADO_USE_CASE'
