/** Tokens de injeção de dependência do módulo loja. */

// Repositórios
export const CLIENTE_REPOSITORY = 'CLIENTE_REPOSITORY'
export const PEDIDO_LOJA_REPOSITORY = 'PEDIDO_LOJA_REPOSITORY'
export const CONFIGURACAO_LOJA_REPOSITORY = 'CONFIGURACAO_LOJA_REPOSITORY'

// Use cases — Auth/Cliente
export const CRIAR_OU_SINCRONIZAR_CLIENTE_USE_CASE = 'CRIAR_OU_SINCRONIZAR_CLIENTE_USE_CASE'
export const OBTER_CLIENTE_USE_CASE = 'OBTER_CLIENTE_USE_CASE'
export const ATUALIZAR_CLIENTE_USE_CASE = 'ATUALIZAR_CLIENTE_USE_CASE'

// Use cases — Endereços
export const LISTAR_ENDERECOS_USE_CASE = 'LISTAR_ENDERECOS_USE_CASE'
export const CRIAR_ENDERECO_USE_CASE = 'CRIAR_ENDERECO_USE_CASE'
export const ATUALIZAR_ENDERECO_USE_CASE = 'ATUALIZAR_ENDERECO_USE_CASE'
export const REMOVER_ENDERECO_USE_CASE = 'REMOVER_ENDERECO_USE_CASE'
export const DEFINIR_ENDERECO_PRINCIPAL_USE_CASE = 'DEFINIR_ENDERECO_PRINCIPAL_USE_CASE'

// Use cases — Pedidos
export const CHECKOUT_PEDIDO_LOJA_USE_CASE = 'CHECKOUT_PEDIDO_LOJA_USE_CASE'
export const LISTAR_PEDIDOS_CLIENTE_USE_CASE = 'LISTAR_PEDIDOS_CLIENTE_USE_CASE'
export const OBTER_PEDIDO_LOJA_USE_CASE = 'OBTER_PEDIDO_LOJA_USE_CASE'
export const CONFIRMAR_PAGAMENTO_PEDIDO_LOJA_USE_CASE = 'CONFIRMAR_PAGAMENTO_PEDIDO_LOJA_USE_CASE'
export const RENOVAR_PIX_PEDIDO_LOJA_USE_CASE = 'RENOVAR_PIX_PEDIDO_LOJA_USE_CASE'

// Use cases — Configuração
export const OBTER_CONFIGURACAO_LOJA_USE_CASE = 'OBTER_CONFIGURACAO_LOJA_USE_CASE'
export const ATUALIZAR_CONFIGURACAO_LOJA_USE_CASE = 'ATUALIZAR_CONFIGURACAO_LOJA_USE_CASE'

// Use cases — Cancelamento
export const SOLICITAR_CANCELAMENTO_PEDIDO_LOJA_USE_CASE = 'SOLICITAR_CANCELAMENTO_PEDIDO_LOJA_USE_CASE'
export const APROVAR_CANCELAMENTO_PEDIDO_LOJA_USE_CASE = 'APROVAR_CANCELAMENTO_PEDIDO_LOJA_USE_CASE'
export const REJEITAR_CANCELAMENTO_PEDIDO_LOJA_USE_CASE = 'REJEITAR_CANCELAMENTO_PEDIDO_LOJA_USE_CASE'

// Use cases — Admin
export const LISTAR_TODOS_PEDIDOS_LOJA_USE_CASE = 'LISTAR_TODOS_PEDIDOS_LOJA_USE_CASE'
export const ATUALIZAR_STATUS_PEDIDO_LOJA_USE_CASE = 'ATUALIZAR_STATUS_PEDIDO_LOJA_USE_CASE'
export const LISTAR_CLIENTES_USE_CASE = 'LISTAR_CLIENTES_USE_CASE'
