export const PROVEDOR_AUTH = 'PROVEDOR_AUTH'
export const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY'
export const ASSOCIADO_REPOSITORY = 'ASSOCIADO_REPOSITORY'

export const CRIAR_USUARIO_USE_CASE = 'CRIAR_USUARIO_USE_CASE'
export const CRIAR_ASSOCIADO_USE_CASE = 'CRIAR_ASSOCIADO_USE_CASE'
export const LISTAR_ASSOCIADOS_USE_CASE = 'LISTAR_ASSOCIADOS_USE_CASE'
export const ATIVAR_USUARIO_USE_CASE = 'ATIVAR_USUARIO_USE_CASE'
export const DESATIVAR_USUARIO_USE_CASE = 'DESATIVAR_USUARIO_USE_CASE'
