/** Tokens de injeção de dependência do módulo de gestão. */
export const ATA_REPOSITORY = 'ATA_REPOSITORY'
export const PARTICIPANTE_ATA_REPOSITORY = 'PARTICIPANTE_ATA_REPOSITORY'
export const DOCUMENTO_REPOSITORY = 'DOCUMENTO_REPOSITORY'
export const STORAGE_PORT = 'STORAGE_PORT'

export const CRIAR_ATA_USE_CASE = 'CRIAR_ATA_USE_CASE'
export const LISTAR_ATAS_USE_CASE = 'LISTAR_ATAS_USE_CASE'
export const PUBLICAR_ATA_USE_CASE = 'PUBLICAR_ATA_USE_CASE'
export const DESPUBLICAR_ATA_USE_CASE = 'DESPUBLICAR_ATA_USE_CASE'
export const ADICIONAR_PARTICIPANTE_USE_CASE = 'ADICIONAR_PARTICIPANTE_USE_CASE'
export const REMOVER_PARTICIPANTE_USE_CASE = 'REMOVER_PARTICIPANTE_USE_CASE'
export const LISTAR_PARTICIPANTES_ATA_USE_CASE = 'LISTAR_PARTICIPANTES_ATA_USE_CASE'

export const CRIAR_DOCUMENTO_USE_CASE = 'CRIAR_DOCUMENTO_USE_CASE'
export const LISTAR_DOCUMENTOS_USE_CASE = 'LISTAR_DOCUMENTOS_USE_CASE'
export const PUBLICAR_DOCUMENTO_USE_CASE = 'PUBLICAR_DOCUMENTO_USE_CASE'
export const DESPUBLICAR_DOCUMENTO_USE_CASE = 'DESPUBLICAR_DOCUMENTO_USE_CASE'
export const EXCLUIR_DOCUMENTO_USE_CASE = 'EXCLUIR_DOCUMENTO_USE_CASE'

export const CONFIGURACAO_REPOSITORY = 'CONFIGURACAO_REPOSITORY'
export const OBTER_CONFIGURACAO_USE_CASE = 'OBTER_CONFIGURACAO_USE_CASE'
export const ATUALIZAR_CONFIGURACAO_USE_CASE = 'ATUALIZAR_CONFIGURACAO_USE_CASE'
